# store variable definitions
db_name = "rds_db_name"
engine = "postgres"
engine_version = "15.4"
instance_class = "db.m5.large"
username = "sayaji"
password = "py{9e4S&4}7"
publicly_accessible = "false"
storage_type = "gp3"
skip_final_snapshot = "true"
db_subnet_group_name = "rds_subnet_group"
allocated_storage = "50"
db_instance_identifier = "rdsidentifier"
max_allocated_storage = "500"
db_security_group_name = "db_sg"
final_snapshot_identifier = "my-final-snapshot"
