name: terraform destroy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branchName:
        description: ''
        required: true
        default: 'main'
jobs:
 terraform_destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init and Plan
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
          cd ./infra/alb
          pwd && ls -la
          terraform init && terraform destroy -auto-approve
          cd ../..
          pwd && ls -la

          cd ./infra/ec2
          pwd && ls -la
          terraform init && terraform destroy -auto-approve
          cd ../..
          pwd && ls -la
          
          cd ./infra/vpc
          terraform init && terraform destroy -auto-approve
          cd ../..
          pwd && ls -la

          cd ./infra/cloudwatch
          pwd && ls -la
          terraform init && terraform destroy -auto-approve
          cd ../..
          
          cd ./infra/sns
          terraform init && terraform destroy -auto-approve
          cd ../..
          pwd 

          cd ./infra/s3
          terraform init && terraform destroy -auto-approve
          cd ../..
          pwd  
          
          
          cd ./infra/cloudfront
          terraform init && terraform destroy -auto-approve
          cd ../..
          pwd           
