name: Terraform CI/CD

on:
 pull_request:
    types: [closed]

jobs:
 terraform_plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init and Plan
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          terraform -version
          ls 
          pwd
          cd ./infra/vpc
          terraform init
          terraform plan

 terraform_deploy:
    needs: terraform_plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Apply
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          cd ./infra/vpc
          terraform init && terraform apply -auto-approve 

  manual_approval_for_destroy:
    runs-on: ubuntu-latest
    needs: terraform_deploy
    steps:
      - name: Manual Approval for Destroy
        id: manual_approval_for_destroy
        uses: wei/ci-approve-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          message: "Approve to destroy the Terraform infrastructure"
          reviewers: "AmitBarate07" 

 
 terraform_destroy:
    needs: terraform_deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Destroy
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          cd ./infra/vpc
          terraform init && terraform destroy -auto-approve
