name: Terraform CI/CD

on:
 pull_request:
    types: [closed]

jobs:
 terraform_init_plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      # - name: Copy SSH key from S3 bucket
      #   run: |
      #     set -x
      #     aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws configure set default.region us-east-1
      #     aws --version
      #     aws s3 ls  
      #     aws s3 cp s3://terra-bct/ec2-key/terraform-key.pem ./infra/alb/


      - name: Terraform Init and Plan
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          echo "launching vpc "
          cd ./infra/vpc
          terraform init && terraform plan && terraform apply -auto-approve
          cd ../..
          pwd && ls -la
          
          echo "launching ec2 "
          cd ./infra/ec2
          terraform init && terraform plan && terraform apply -auto-approve
          cd ../..
          pwd && ls -la
          
          echo "launching alb "
          cd ./infra/alb
          ls -la
          terraform init && terraform plan && terraform apply -auto-approve  
          cd ../..      

          echo "launching sns topic "
          cd ./infra/sns
          ls -la
          terraform init && terraform plan && terraform apply -auto-approve  
          cd ../..          

          echo "launching cloudwatch "
          cd ./infra/cloudwatch
          ls -la
          terraform init && terraform plan && terraform apply -auto-approve  

#########################################################################################
#  terraform_apply:
#     needs: terraform_init_plan
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2
#         with:
#           ref: main

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v1

#       - name: Terraform Apply
#         run: |
#           export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
#           export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           # cd ./infra/vpc
#           # terraform init && terraform apply -auto-approve
#           # cd ../..
#           # pwd && ls -la
          
#           # cd ./infra/ec2
#           # pwd && ls -la
#           # terraform init && terraform apply -auto-approve

#           cd ./infra/alb
#           terraform init && terraform plan && terraform apply -auto-approve
          
